### ISSUE TITLE
纵向错乱

### ISSUE THREAD

**Issue by ghostman-git** [zhangzhen1979/JIMU-ConvertPreview#1]
![image](https://user-images.githubusercontent.com/13376074/161919837-7ed98211-0e45-4b26-86e6-6b33c91a7009.png)

![image](https://user-images.githubusercontent.com/13376074/161919894-c91f9294-178d-4a6f-bfaa-6e9fe82670fa.png)

https://gitee.com/ghostman/document/raw/master/%E6%8A%A5%E9%94%80%E5%8D%95.pdf

**Comment by ltian1018** [comment]
请提供对应的原始文件用于bug排查

**Comment by ghostman-git** [comment]
> 请提供对应的原始文件用于bug排查

https://gitee.com/ghostman/document/raw/master/%E6%8A%A5%E9%94%80%E5%8D%95.pdf

**Comment by ltian1018** [comment]
经测试，word、excel纵向表格转pdf，均未出现错乱问题。
版本信息

- jdk：1.8.0_144
- LibreOffice： 7.3

图示（表格内容通过OCR进行识别，部分字段不准确）：
doc 转 pdf
https://cdn.nlark.com/yuque/0/2022/png/181014/1649730063013-87085bd2-7ac1-441d-8ac1-506c09d5cf6d.png

xlsx 转 pdf
https://cdn.nlark.com/yuque/0/2022/png/181014/1649730239646-0462121b-8440-4021-8b52-6cd3b5a8c080.png

如需继续排查，请提供原始输入文件、输入参数用于继续追踪。

**Comment by ghostman-git** [comment]
> 经测试，word、excel纵向表格转pdf，均未出现错乱问题。 版本信息
> 
> * jdk：1.8.0_144
> * LibreOffice： 7.3
> 
> 图示（表格内容通过OCR进行识别，部分字段不准确）： doc 转 pdf https://cdn.nlark.com/yuque/0/2022/png/181014/1649730063013-87085bd2-7ac1-441d-8ac1-506c09d5cf6d.png
> 
> xlsx 转 pdf https://cdn.nlark.com/yuque/0/2022/png/181014/1649730239646-0462121b-8440-4021-8b52-6cd3b5a8c080.png
> 
> 如需继续排查，请提供原始输入文件、输入参数用于继续追踪。


是pdf转odf出现问题，提供下pdf文件：https://gitee.com/ghostman/document/raw/master/%E6%8A%A5%E9%94%80%E5%8D%95.pdf

**Comment by zhangzhen1979** [comment]
经测试，未发现此问题。
